import { CardDesc } from './types'

const cards: Array<CardDesc> = [
    { src: './assets/6_бубны.png', notation: '6D' },
    { src: './assets/7_бубны.png', notation: '7D' },
    { src: './assets/8_бубны.png', notation: '8D' },
    { src: './assets/9_бубны.png', notation: '9D' },
    { src: './assets/10_бубны.png', notation: '10D' },
    { src: './assets/валет_бубны.png', notation: 'JD' },
    { src: './assets/дама_бубны.png', notation: 'QD' },
    { src: './assets/король_бубны.png', notation: 'KD' },
    { src: './assets/туз_бубны.png', notation: 'AD' },
    { src: './assets/6_черви.png', notation: '6H' },
    { src: './assets/7_черви.png', notation: '7H' },
    { src: './assets/8_черви.png', notation: '8H' },
    { src: './assets/9_черви.png', notation: '9H' },
    { src: './assets/10_черви.png', notation: '10H' },
    { src: './assets/валет_черви.png', notation: 'JH' },
    { src: './assets/дама_черви.png', notation: 'QH' },
    { src: './assets/король_черви.png', notation: 'KH' },
    { src: './assets/туз_черви.png', notation: 'AH' },
    { src: './assets/6_крести.png', notation: '6C' },
    { src: './assets/7_крести.png', notation: '7C' },
    { src: './assets/8_крести.png', notation: '8C' },
    { src: './assets/9_крести.png', notation: '9C' },
    { src: './assets/10_крести.png', notation: '10C' },
    { src: './assets/валет_крести.png', notation: 'JC' },
    { src: './assets/дама_крести.png', notation: 'QC' },
    { src: './assets/король_крести.png', notation: 'KC' },
    { src: './assets/туз_крести.png', notation: 'AC' },
    { src: './assets/6_пики.png', notation: '6S' },
    { src: './assets/7_пики.png', notation: '7S' },
    { src: './assets/8_пики.png', notation: '8S' },
    { src: './assets/9_пики.png', notation: '9S' },
    { src: './assets/10_пики.png', notation: '10S' },
    { src: './assets/валет_пики.png', notation: 'JS' },
    { src: './assets/дама_пики.png', notation: 'QS' },
    { src: './assets/король_пики.png', notation: 'KS' },
    { src: './assets/туз_пики.png', notation: 'AS' },
]

export default cards
