export type CardDesc = {
    src: string,
    notation: string
}

type Cards = {
    0: CardDesc,
    1: CardDesc,
    2: CardDesc,
    3: CardDesc,
    4: CardDesc,
    5: CardDesc,
    6: CardDesc,
    7: CardDesc,
    8: CardDesc,
    9: CardDesc,
    10: CardDesc,
    11: CardDesc,
    12: CardDesc,
    13: CardDesc,
    14: CardDesc,
    15: CardDesc,
    16: CardDesc,
    17: CardDesc,
    18: CardDesc,
    19: CardDesc,
    20: CardDesc,
    21: CardDesc,
    22: CardDesc,
    23: CardDesc,
    24: CardDesc,
    25: CardDesc,
    26: CardDesc,
    27: CardDesc,
    28: CardDesc,
    29: CardDesc,
    30: CardDesc,
    31: CardDesc,
    32: CardDesc,
    33: CardDesc,
    34: CardDesc,
    35: CardDesc
}

const cards: Cards = {
    0: { src: './assets/6_бубны.png', notation: '6D' },
    1: { src: './assets/7_бубны.png', notation: '7D' },
    2: { src: './assets/8_бубны.png', notation: '8D' },
    3: { src: './assets/9_бубны.png', notation: '9D' },
    4: { src: './assets/10_бубны.png', notation: '10D' },
    5: { src: './assets/валет_бубны.png', notation: 'JD' },
    6: { src: './assets/дама_бубны.png', notation: 'QD' },
    7: { src: './assets/король_бубны.png', notation: 'KD' },
    8: { src: './assets/туз_бубны.png', notation: 'AD' },
    9: { src: './assets/6_черви.png', notation: '6H' },
    10: { src: './assets/7_черви.png', notation: '7H' },
    11: { src: './assets/8_черви.png', notation: '8H' },
    12: { src: './assets/9_черви.png', notation: '9H' },
    13: { src: './assets/10_черви.png', notation: '10H' },
    14: { src: './assets/валет_черви.png', notation: 'JH' },
    15: { src: './assets/дама_черви.png', notation: 'QH' },
    16: { src: './assets/король_черви.png', notation: 'KH' },
    17: { src: './assets/туз_черви.png', notation: 'AH' },
    18: { src: './assets/6_крести.png', notation: '6C' },
    19: { src: './assets/7_крести.png', notation: '7C' },
    20: { src: './assets/8_крести.png', notation: '8C' },
    21: { src: './assets/9_крести.png', notation: '9C' },
    22: { src: './assets/10_крести.png', notation: '10C' },
    23: { src: './assets/валет_крести.png', notation: 'JC' },
    24: { src: './assets/дама_крести.png', notation: 'QC' },
    25: { src: './assets/король_крести.png', notation: 'KC' },
    26: { src: './assets/туз_крести.png', notation: 'AC' },
    27: { src: './assets/6_пики.png', notation: '6S' },
    28: { src: './assets/7_пики.png', notation: '7S' },
    29: { src: './assets/8_пики.png', notation: '8S' },
    30: { src: './assets/9_пики.png', notation: '9S' },
    31: { src: './assets/10_пики.png', notation: '10S' },
    32: { src: './assets/валет_пики.png', notation: 'JS' },
    33: { src: './assets/дама_пики.png', notation: 'QS' },
    34: { src: './assets/король_пики.png', notation: 'KS' },
    35: { src: './assets/туз_пики.png', notation: 'AS' },
}

export default cards
